print("-------------------------------------")
print("S.No   Name           Subject   Marks")
print("-------------------------------------")
print("1.     Deepak         English   86.50")
print("2.     Deepak         Tamil     95.00")
print("3.     Deepak         Maths     75.50")
print("4.     Prince         English   96.50")
print("5.     Prince         Tamil     80.50")
print("6.     Prince         Maths     98.50")
print("-------------------------------------")
